
-- Jalankan di Supabase SQL Editor jika tabel belum tersedia.
-- Jika tabel sudah ada, sesuaikan hanya bagian yang belum dibuat.

create table if not exists public.profiles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    name text not null default '',
    age integer,
    sex text,
    height_cm numeric,
    weight_kg numeric,
    activity text,
    goal text,
    calorie_target numeric,
    protein_target numeric,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.meals (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    meal_date date not null default current_date,
    meal_type text not null,
    food_name text not null,
    grams numeric not null,
    calories numeric,
    protein_g numeric,
    fat_g numeric,
    carbs_g numeric,
    fiber_g numeric,
    sugar_g numeric,
    sodium_mg numeric,
    source text,
    created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.meals enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;

create policy "profiles_select_own"
on public.profiles for select
to authenticated
using (auth.uid() = user_id);

create policy "profiles_insert_own"
on public.profiles for insert
to authenticated
with check (auth.uid() = user_id);

create policy "profiles_update_own"
on public.profiles for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "meals_select_own" on public.meals;
drop policy if exists "meals_insert_own" on public.meals;
drop policy if exists "meals_update_own" on public.meals;
drop policy if exists "meals_delete_own" on public.meals;

create policy "meals_select_own"
on public.meals for select
to authenticated
using (auth.uid() = user_id);

create policy "meals_insert_own"
on public.meals for insert
to authenticated
with check (auth.uid() = user_id);

create policy "meals_update_own"
on public.meals for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "meals_delete_own"
on public.meals for delete
to authenticated
using (auth.uid() = user_id);
